### ISSUE TITLE
GenerateContentRequest object is missing

### ISSUE THREAD

**Issue by nikolaydubina** [googleapis/go-genai#505]
Thanks for stopping by to let us know something could be better!

**Is your feature request related to a problem? Please describe.**

`GenerateContentRequest` struct is missing in this pkg API, but it is key type in Batch API mode for GenAI.

`InlinedRequest` is incompatible, because it has `config` field, meanwhile `GenerateContentRequest` expects contents of `config` such as `systemInstruction` to be inliend in root.

https://ai.google.dev/api/batch-mode#GenerateContentRequest

**Describe the solution you'd like**
I would like to have https://ai.google.dev/api/batch-mode#GenerateContentRequest

**Describe alternatives you've considered**

- `InlinedRequest` - not compatible
- defining my own struct in my own codebase

**Additional context**

N/A

**Comment by qiaodev** [comment]
Thanks for reporting the issue. We are working on fix it. I will update to this thread when the fix is avaiable.

**Comment by qiaodev** [comment]
System instruction issue is fixed at https://github.com/googleapis/go-genai/pull/522.

Example code can be found at https://github.com/googleapis/go-genai/pull/522/files#diff-3b49f374b2b3a0ac8bd45868fca31600670705c2fa520e926f315bbd59b52c3a

**Comment by nikolaydubina** [comment]
nope, this issue is still not fixed

**Comment by qiaodev** [comment]
I wonder whether https://github.com/googleapis/go-genai/pull/522/files#diff-3b49f374b2b3a0ac8bd45868fca31600670705c2fa520e926f315bbd59b52c3a passes on your end?

And do you have any code snippet to help me reproduce the issue?

**Comment by nikolaydubina** [comment]
hey @qiaodev, no this does not help. try to do Batch API inference WITHOUT inlined request. issue is still not fixed.
